import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // Navbar & Footer
    home: 'Home',
    about: 'About Us',
    donate: 'Donate Blood',
    requestBlood: 'Request Blood',
    trackRequests: 'Track Requests',
    bloodCamps: 'Blood Camps',
    volunteers: 'Volunteers',
    gallery: 'Gallery',
    contact: 'Contact Us',
    loginRegister: 'Login / Register',
    portal: 'Portal',
    logout: 'Logout',
    tagline: 'Donate Blood, Save Lives',
    selectLanguage: 'Select Language',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    marathi: 'मराठी (Marathi)',
    quickLinks: 'Quick Links',
    contactInfo: 'Contact Info',
    allRightsReserved: 'All rights reserved.',
    footerDesc: 'Blood Trust is a non-profit voluntary blood donor network connecting willing donors with certified partner hospitals.',

    // Hero Section
    heroBadge: 'EMERGENCY BLOOD DONOR NETWORK',
    heroTitleLine1: 'One Donation',
    heroTitleLine2: 'Can ',
    heroTitleHighlight: 'Save Many Lives',
    heroSubtitle: 'Be a hero. Donate blood and make a difference in someone\'s life.',
    donateNow: 'Donate Now',
    learnMore: 'Learn More',
    findBloodStock: 'Find Blood Stock',
    emergencyRequest: 'Emergency Request',
    viewCampSchedule: 'View Camp Schedule',
    registerAsDonor: 'Register as Donor',
    checkEligibility: 'Check Eligibility',
    donorFAQ: 'Donor FAQ',
    viewGallery: 'View Our Gallery',

    // Hero Slider Translations
    slide1Title1: 'Bombay Blood Group Org',
    slide1Title2: 'National ',
    slide1Highlight: 'Award Function',
    slide1Sub: 'Recognizing excellence in voluntary blood donation and lifesaving social services.',
    
    slide2Title1: 'Felicitation by Governor',
    slide2Title2: 'Honored for ',
    slide2Highlight: 'Selfless Service',
    slide2Sub: 'Honored by Hon\'ble Governor of Maharashtra Bhagat Singh Koshyari for outstanding social work.',

    slide3Title1: 'National Award 2018',
    slide3Title2: 'Saving Lives ',
    slide3Highlight: 'Together',
    slide3Sub: 'Celebrating voluntary blood donors and organizers recognized at the National Award function.',

    slide4Title1: 'Every Drop Counts',
    slide4Title2: 'Our Dedicated ',
    slide4Highlight: 'Donor Network',
    slide4Sub: 'Empowering communities with 100% safe, certified, and voluntary blood donation camps.',

    // 4 Quick Service Cards
    becomeDonor: 'Become a Donor',
    becomeDonorDesc: 'Join our mission and save countless lives.',
    registerNow: 'Register Now',
    checkEligibilityCardDesc: 'Evaluate your health & donor readiness in seconds.',
    checkNow: 'Check Now',
    contactUsCardDesc: 'Get in touch 24/7 for emergency help and inquiries.',
    contactNow: 'Contact Now',
    contactUs: 'Contact Us',
    requestBloodTitle: 'Request Blood',
    requestBloodDesc: 'Need blood? Submit a request and we\'ll help.',
    requestNow: 'Request Now',
    findBlood: 'Find Blood',
    findBloodDesc: 'Search blood availability in your area.',
    searchNow: 'Search Now',
    campsTitle: 'Blood Camps',
    campsDesc: 'Find and join upcoming blood donation camps.',
    viewCamps: 'View Camps',

    // Key Statistics
    happyDonors: 'Happy Donors',
    unitsDonated: 'Units Donated',
    partnerHospitals: 'Partner Hospitals',
    campsCount: 'Blood Camps',

    // About Section on Home
    aboutUsBadge: 'ABOUT US',
    aboutUsTitle: 'We Are Here to Save Lives',
    aboutUsDesc: 'Blood Trust is a non-profit organization working tirelessly to bridge the gap between blood donors and those in need. Together, we can build a healthier and stronger community.',
    knowMoreAboutUs: 'Know More About Us',
    safeSecure: 'Safe & Secure',
    safeSecureDesc: 'We follow strict protocols to ensure 100% safe blood donation.',
    trustedNetwork: 'Trusted Network',
    trustedNetworkDesc: 'Connected with certified blood banks and hospitals.',
    support247: '24/7 Support',
    support247Desc: 'We are always here to help you anytime.',

    // Vision & Mission Section
    ourPurpose: 'OUR PURPOSE & CORE VALUES',
    ourVisionMission: 'Our Vision & Mission',
    ourVisionMissionDesc: 'Guided by compassion and dedication to build a safer, self-sufficient voluntary blood donor community.',
    ourVision: 'Our Vision',
    visionTitle: 'Zero Lives Lost Due to Blood Shortage',
    visionDesc: 'To build a 100% voluntary, digitally synchronized blood donor network across the nation where no emergency patient ever suffers due to non-availability of safe, compatible blood.',
    visionPoint1: '100% Voluntary Blood Donor Community',
    visionPoint2: 'Seamless Regional Hospital Connectivity',
    visionPoint3: 'Transparent & Safe Health Protocols',
    ourMission: 'Our Mission',
    missionTitle: 'Mobilizing Donors & Empowering Communities',
    missionDesc: 'To empower citizens with accessible donor tools, organize regular blood donation drives, educate youth, and rapidly connect willing donors with partner healthcare institutions in critical moments.',
    missionPoint1: 'Verified Digital Lifesaver Registry',
    missionPoint2: 'Community & Corporate Blood Camps',
    missionPoint3: '24/7 Rapid Lifesaver Matching',

    // Who Can Donate Section
    whoCanDonate: 'Who Can Donate Blood?',
    whoCanDonateDesc: 'Donating blood is a simple, safe and life-saving act. Check your health eligibility questionnaire down below.',
    whoCanDonateText2: 'Down below is a Questionnaire provided to assess the Health percentage based on general norms.',
    findNearbyCamps: 'Find Nearby Camps',

    // Blood Camps Section
    upcomingBloodCamps: 'Upcoming Blood Camps',
    viewAllCamps: 'View All Camps',
    organizeCamp: 'Organize a Blood Camp',
    bookCampSlot: 'Book Camp Slot',

    // Testimonials
    whatDonorsSay: 'What Donors Say',
    testimonial1: 'Donating blood was the best decision I made. It felt amazing to know I could save a life.',
    testimonial2: 'The process was so smooth and the team was very supportive. Highly recommend!',
    testimonial3: 'A small act of kindness can make a big difference. Proud to be a regular donor.',

    // Gallery Page
    ourGallery: 'Our Media & Press Gallery',
    gallerySub: 'Authentic press clippings, Governor felicitations, and national recognition awards celebrating our voluntary blood donation drives and rare Bombay blood group lifesaver initiatives.',
    allMedia: 'All Press Media',
    photos: 'Newspaper Clippings',
    videos: 'Videos',
    camps: 'Blood Drives',
    awareness: 'Rare Bombay Group',
    awards: 'State & National Awards',
    searchGallery: 'Search press gallery...',
    mediaPhotoBadge: 'PRESS CLIPPING',
    mediaVideoBadge: 'VIDEO',
    
    // Real Press & Newspaper Clippings (Total: 20 Items)
    gItem1Title: 'Appasaheb Ghorpade Honored with National Award',
    gItem1Sub: 'Recognized for outstanding voluntary blood donation work with Adarsh Blood Donor 2021 Award.',
    
    gItem2Title: '50+ Milestone Donations of Rare Bombay Blood Group',
    gItem2Sub: 'Vikram Yadav completes 54+ voluntary donations of the extremely rare Bombay Blood Group, saving lives nationwide.',
    
    gItem3Title: 'Felicitation by Hon\'ble Governor Bhagat Singh Koshyari',
    gItem3Sub: 'Bombay Blood Group honored at Raj Bhavan by Governor Bhagat Singh Koshyari for selfless Covid-19 lifesaver services.',
    
    gItem4Title: 'Kartavyadaksha Puraskar Awarded to Bombay O Group',
    gItem4Sub: 'Honored by Grahak Panchayat for exemplary voluntary blood distribution network and selfless service.',
    
    gItem5Title: '66th Rare Bombay Blood Group Donation in Sindhudurg',
    gItem5Sub: 'Emergency journey to Sindhudurg to save a critical patient needing extremely rare Bombay Blood Group.',

    gItem6Title: 'Vikram Yadav - 1 of 179 Rare Bombay Blood Donors in India',
    gItem6Sub: 'Sakal Press Feature: Completing 50+ rare Bombay blood group donations and establishing a network across 22 states with 570 branches.',

    gItem7Title: 'Supply of Rare Bombay Blood Group Across 22 Indian States',
    gItem7Sub: 'Tarun Bharat World Blood Donor Day Special: Vikram Yadav\'s network supplies rare Bombay Blood Group across 22 states with 570 active branches.',

    gItem8Title: 'Bombay Blood Group Work Inspiring: Dr. Manoj Ingale',
    gItem8Sub: 'Pudhari Press Clipping: National Award Ceremony at Tasgaon honoring 45 blood donation organizations across 22 Indian states and 5 international NGOs.',

    gItem9Title: 'Blood Shortage Awareness Campaign in Sangli District',
    gItem9Sub: 'Lokmat Info Story: Emergency campaign mobilizing voluntary blood donors during severe summer blood bank shortages.',

    gItem10Title: 'People with Gold in Their Veins - Rare Bombay Blood Donors',
    gItem10Sub: 'Mid-day Special Feature by C Y Gopinath: Highlighting selfless Bombay Blood Group donors who travel nationwide to save strangers\' lives.',

    gItem11Title: 'Maharashtra Donors Rush to Save Karnataka Infant\'s Life',
    gItem11Sub: 'Lokmat Front Page Report: Emergency lifesaver Bombay blood donation arranged by Vikram Yadav\'s group for a 1-year-old child undergoing surgery in Bijapur, Karnataka.',

    gItem12Title: 'Maharashtra & Konkan Donors Rush to Save Karnataka Infant\'s Life',
    gItem12Sub: 'Bandhuta News: Lifesaving rare Bombay Blood donation by Onkar Dhanavade (Dapoli) and Hanumant Bhosale (Sangli) for a 1-year-old child in Babaleshwar, Karnataka.',

    gItem13Title: 'Compassion in Blood - Story of Lifesaver Vikram Yadav',
    gItem13Sub: 'Special Profile: Highlighting Vikram Yadav\'s 68+ voluntary donations and emergency travels to Jharkhand, Delhi, Agra, Kerala, and Hyderabad.',

    gItem14Title: 'Rare Bombay Blood Airlifted from Kolhapur to Hyderabad Patient',
    gItem14Sub: 'Sakal Front Page Feature: Emergency flight dispatch of rare Bombay Blood from Kolhapur to Apollo Hospital Hyderabad for a 61-year-old heart surgery patient.',

    gItem15Title: 'Grand Blood Donation Camp Organized at Kavathepiran',
    gItem15Sub: 'Adhunik Kesari News: 85 blood units collected at Miraj drive organized by Bombay Blood Group & Hind Kesari Club.',

    gItem16Title: 'Vikram Yadav Honored with National Award in Jharkhand',
    gItem16Sub: 'Adhunik Kesari News: National Award conferred by Roti Blood Youth Club at Dhanbad, Jharkhand to Vikram Yadav for 69+ donations across India.',

    gItem17Title: 'Bombay Blood Group Proves to Be Lifesaving Angels for Patients',
    gItem17Sub: 'Tarun Bharat Report: Emergency Bombay blood donation dispatch for Ayum Karba in Bijapur Hospital, Karnataka organized by Vikram Yadav, Atul Chougule, Dheeraj Patil.',

    gItem18Title: 'Sangli District Becomes Voluntary Donor Hub Under Vikram Yadav\'s Leadership',
    gItem18Sub: 'Special Press Feature: Emergency Bombay blood donation at Bharati Hospital Miraj organized by Vikram Yadav, Sunil Bhosale, Prashant Bele, Suraj Deshmukh.',

    gItem19Title: '5 Bags of Extremely Rare Bombay Blood Supplied in 1 Single Day',
    gItem19Sub: 'Lokmat Must Read: Emergency record dispatch of 5 Bombay blood units simultaneously across Delhi, Raipur, Solapur, Pune, and Mumbai hospitals.',

    gItem20Title: 'Bombay Blood Group Tasgaon Honored with Maharashtra Gaurav Sanman',
    gItem20Sub: 'Eagle News Report: President Vikram Yadav & team awarded Shri Chhatrapati Shivaji Maharaj Maharashtra Gaurav Sanman at Malad, Mumbai by Arihantnayak Rakt Sarthi Sanstha Rajasthan.',

    // Form Field Labels (Register / Login / Contact)
    fullName: 'FULL NAME',
    emailAddress: 'EMAIL ADDRESS',
    phoneNumber: 'PHONE NUMBER',
    password: 'PASSWORD',
    bloodGroup: 'BLOOD GROUP',
    cityRegion: 'CITY / REGION',
    weightKg: 'WEIGHT (KG)',
    rarePhenotypeCheck: 'Check here if you belong to a Rare Phenotype (e.g. Bombay Blood, Rh-null).',
    donorRegistrationTitle: 'Donor Registration',
    donorRegistrationSub: 'Join the life-saving network. It takes less than 2 minutes.',

    // Page Specific Headers
    availabilityPageTitle: 'Real-Time Blood Availability & Inventory',
    availabilityPageDesc: 'Search live blood stock across certified depositories, regional blood banks, and partner hospitals.',
    directoryPageTitle: 'Blood Bank & Hospital Directory',
    directoryPageDesc: 'Locate certified blood depositories with interactive Google Map embed and real-time contact details.',
    contactPageTitle: 'Contact Our Emergency Helpline',
    contactPageDesc: 'Have questions or need emergency assistance? Reach out to our 24/7 support team.',
    galleryPageTitle: 'Blood Trust Media & Newspaper Archives',

    // Auth Pages
    welcomeBack: 'Welcome Back',
    loginAccount: 'Login to Your Account',
    createDonorAccount: 'Create New Donor Account',
    loginBtn: 'Login to Account',
    registerBtn: 'Register as Lifesaver',

    // Admin Dashboard Translations
    adminPortalTitle: 'Admin Portal',
    overview: 'Overview',
    donorManagement: 'Donor Management',
    whatWeDo: 'What We Do',
    settings: 'Settings',
    support: 'Support',
    registerNewDonor: 'Register New Donor',
    adminOverviewTitle: 'Blood Trust Admin Overview',
    adminOverviewSub: 'High-level summary of voluntary donor network & community operations.',
    totalDonors: 'Total Registered Donors',
    eligibleDonors: 'Eligible Donors',
    campsOrganized: 'Blood Camps Organized',
    connectedHospitals: 'Connected Hospitals',
    searchDonorsPlaceholder: 'Search donors, ID, contact...',
    donorId: 'Donor ID',
    donorName: 'Donor Name',
    lastDonation: 'Last Donation',
    status: 'Status',
    actions: 'Actions',
    recentRegistrations: 'Recent Donor Registrations',
    viewAllDonors: 'View All Donors',

    // Admin CMS Tab Translations
    pageCms: 'Page Text & Image CMS',
    cmsTitle: 'Website Text & Image CMS',
    cmsDesc: 'Edit text headings, descriptions, statistics, and image links live across the entire website.',
    resetDefaults: 'Reset Defaults',
    subTabHero: 'Hero Banner Slider',
    subTabVision: 'Vision & Mission',
    subTabAbout: 'About Us Section',
    subTabStats: 'Key Statistics',
    subTabGallery: 'Media Gallery Items',
    heroSlidesTitle: 'Hero Banner Slides',
    heroSlidesSub: 'Add, edit, or delete banner slides rendered on the homepage.',
    addNewSlide: 'Add New Slide',
    saveSlides: 'Save Slides',
    imageUrlLabel: 'Image URL / File Path',
    titlePrefixLabel: 'Title Prefix (Line 1)',
    highlightWordLabel: 'Highlight Word',
    subtitleLabel: 'Subtitle / Description',
    vmSectionTitle: 'Vision & Mission Section Text',
    vmSectionSub: 'Edit titles, descriptions, and feature keypoints.',
    saveVm: 'Save Vision & Mission',
    aboutUsCmsTitle: 'About Us Section',
    aboutUsCmsSub: 'Edit homepage about section title and description.',
    saveAboutUs: 'Save About Us',
    sectionBadgeTag: 'Section Badge Tag',
    mainTitleLabel: 'Main Title',
    mainDescLabel: 'Main Description Text',
    keyStatsCmsTitle: 'Key Impact Statistics',
    keyStatsCmsSub: 'Edit donor count, units donated, partner hospitals, and camp numbers.',
    saveStats: 'Save Statistics',
    labelHappyDonors: 'Happy Donors Registered',
    labelUnitsDonated: 'Blood Units Donated',
    labelPartnerHospitals: 'Partner Hospitals',
    labelCampsCount: 'Blood Camps Organized',
    galleryCmsTitle: 'Media Gallery Items',
    galleryCmsSub: 'Add new press news clippings, edit titles/subtext, or delete items.',
    addNewNewspaperItem: 'Add Newspaper Item',
    saveGalleryItems: 'Save Gallery Items',
    headlineTitleLabel: 'Headline / Title',
    subtextSummaryLabel: 'Subtext / Summary',
    dateLabel: 'Date',
    locationSourceLabel: 'Location / Source',
    subTabContact: 'Contact Us Info',
    subTabOther: 'Eligibility & Camps Pages',
    contactCmsTitle: 'Contact Us Page Info',
    contactCmsSub: 'Edit emergency hotline number, inquiry email, headquarters address, and description.',
    emergencyLineLabel: '24/7 Emergency Line / Phone',
    emailInquiryLabel: 'General Email Inquiry',
    headquartersLabel: 'Headquarters Address',
    contactDescLabel: 'Contact Info Description',
    otherCmsTitle: 'Eligibility Criteria & Blood Camps CMS',
    otherCmsSub: 'Edit subtitles and eligibility guidelines rendered on public pages.',
    campsSubtitleLabel: 'Blood Camps Page Subtitle',
    eligSubtitleLabel: 'Eligibility Page Subtitle',
    ageDescLabel: 'Age Limit Description',
    weightDescLabel: 'Weight Requirement Description',
    hemoDescLabel: 'Hemoglobin Level Description',
    intervalDescLabel: 'Donation Interval Description',
    saveContact: 'Save Contact Info',
    saveOther: 'Save Page Guidelines',
    subTabAboutPage: 'About Us Page CMS',
    subTabDonatePage: 'Donate Blood Page CMS',
    subTabGalleryPage: 'Media Gallery Page CMS',
    aboutPageCmsTitle: 'About Us Page Content & Stat Cards',
    aboutPageCmsSub: 'Edit top header title, subtitle, purpose & core values text, and add/edit stat cards.',
    addNewStatCard: '+ Add New Stat Card',
    saveAboutPage: 'Save About Us Page',
    donateCmsTitle: 'Donate Blood Page Header',
    donateCmsSub: 'Edit donor registration page heading and subtext.',
    saveDonate: 'Save Donate Blood Page',
    galleryHeaderCmsTitle: 'Gallery Page Banner & Clippings',
    galleryHeaderCmsSub: 'Edit top press archives badge, main title, subtitle, and newspaper items.',
    badgeLabel: 'Badge / Tag Line',
    statValueLabel: 'Stat Value (e.g. 100%, 200+, Zero)',
    statLabelText: 'Stat Card Label Text',
    aboutPageTitle: 'About Us',
    aboutPageSubtitle: 'Blood Trust is a non-profit voluntary blood donor network connecting willing donors with certified partner hospitals.',
    aboutPagePurposeTitle: 'OUR PURPOSE & CORE VALUES',
    aboutPagePurposeDesc1: 'To build a 100% voluntary, digitally synchronized blood donor network across the nation where no emergency patient ever suffers due to non-availability of safe, compatible blood.',
    aboutPagePurposeDesc2: 'To empower citizens with accessible donor tools, organize regular blood donation drives, educate youth, and rapidly connect willing donors with partner healthcare institutions in critical moments.',
    zeroFees: 'Zero Commercial Fees',
    isoCertified: 'ISO Certified Protocol',

    // Additional Page & Component UI Translations
    ageLimit: 'Age Limit',
    ageLimitDesc: 'Between 18 and 65 years old (17 with parental consent in select regions).',
    minWeight: 'Minimum Weight',
    minWeightDesc: 'At least 50 kg (110 lbs) for standard 450ml donation.',
    hemoglobinLevel: 'Hemoglobin Level',
    hemoglobinLevelDesc: 'Minimum 12.5 g/dL tested on-site prior to donation.',
    donationInterval: 'Donation Interval',
    donationIntervalDesc: '90 days (3 months) for men; 120 days (4 months) for women.',
    qAge: 'Are you between 18 and 65 years old?',
    qWeight: 'Is your body weight at least 50 kg?',
    qGap: 'Has it been at least 3 months since your last donation?',
    eligibleSuccessTitle: 'Preliminary Assessment: ELIGIBLE',
    eligibleSuccessDesc: 'You appear to meet standard health criteria. Register as a donor to save lives.',
    ineligibleTitle: 'Preliminary Assessment: INELIGIBLE',
    ineligibleDesc: 'Please review medical guidelines or consult a physician before donating.',
    mediaRecognition: 'Media Recognition',
    gallerySubtitle: 'Lives Saved. Hope Restored. Discover our authentic newspaper clippings, awards, and blood donation press coverage.',
    viewFullDetails: 'View Full Details',
    details: 'Details',
    pressClipping: 'Press Clipping',
    viewAllClippings: 'View All 20 Clippings in Gallery',
    emergencyLine: '24/7 Emergency Line',
    emailInquiry: 'General Email Inquiry',
    headquarters: 'Headquarters',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    subject: 'Subject',
    message: 'Message',
    sendMessage: 'Send Message',
    messageSent: 'Message Sent Successfully!',
    messageSentDesc: 'Thank you for contacting Blood Trust. A representative will respond to your query within 24 hours.',
    sendAnother: 'Send Another Message'
  },

  hi: {
    // Navbar & Footer
    home: 'होम',
    about: 'हमारे बारे में',
    donate: 'रक्तदान करें',
    requestBlood: 'रक्त अनुरोध',
    trackRequests: 'अनुरोध ट्रैक करें',
    bloodCamps: 'रक्तदान शिविर',
    volunteers: 'स्वयंसेवक',
    gallery: 'गैलरी',
    contact: 'संपर्क करें',
    loginRegister: 'लॉगिन / रजिस्टर',
    portal: 'पोर्टल',
    logout: 'लॉगआउट',
    tagline: 'रक्तदान करें, जीवन बचाएं',
    selectLanguage: 'भाषा चुनें',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    marathi: 'मराठी (Marathi)',
    quickLinks: 'त्वरित लिंक',
    contactInfo: 'संपर्क जानकारी',
    allRightsReserved: 'सर्वाधिकार सुरक्षित।',
    footerDesc: 'ब्लड ट्रस्ट एक गैर-लाभकारी स्वैच्छिक रक्तदाता नेटवर्क है जो इच्छुक दाताओं को प्रमाणित अस्पतालों से जोड़ता है।',

    // Hero Section
    heroBadge: 'आपत्कालीन रक्तदान नेटवर्क',
    heroTitleLine1: 'एक रक्तदान',
    heroTitleLine2: 'कई ',
    heroTitleHighlight: 'जीवन बचा सकता है',
    heroSubtitle: 'हीरो बनें। रक्तदान करें और किसी के जीवन में बदलाव लाएं।',
    donateNow: 'अभी रक्तदान करें',
    learnMore: 'अधिक जानें',
    findBloodStock: 'रक्त स्टॉक खोजें',
    emergencyRequest: 'आपत्कालीन अनुरोध',
    viewCampSchedule: 'शिविर अनुसूची देखें',
    registerAsDonor: 'रक्तदाता पंजीकरण',
    checkEligibility: 'पात्रता जांचें',
    donorFAQ: 'दाता पूछे जाने वाले प्रश्न',
    viewGallery: 'गैलरी देखें',

    // Hero Slider Translations
    slide1Title1: 'बॉम्बे ब्लड ग्रुप संस्था',
    slide1Title2: 'राष्ट्रीय ',
    slide1Highlight: 'पुरस्कार समारोह',
    slide1Sub: 'स्वैच्छिक रक्तदान और जीवन रक्षक सामाजिक सेवाओं में उत्कृष्ट कार्य की सराहना।',

    slide2Title1: 'राज्यपाल द्वारा सम्मान',
    slide2Title2: 'निस्वार्थ सेवा हेतु ',
    slide2Highlight: 'सम्मानित',
    slide2Sub: 'महाराष्ट्र के माननीय राज्यपाल भगत सिंह कोश्यारी द्वारा उत्कृष्ट सामाजिक कार्य हेतु सम्मानित।',

    slide3Title1: 'राष्ट्रीय पुरस्कार 2018',
    slide3Title2: 'एक साथ ',
    slide3Highlight: 'जीवन बचाते हुए',
    slide3Sub: 'राष्ट्रीय पुरस्कार समारोह में सम्मानित स्वैच्छिक रक्तदाताओं और आयोजकों का अभिनंदन।',

    slide4Title1: 'हर बूंद कीमती है',
    slide4Title2: 'हमारा समर्पित ',
    slide4Highlight: 'रक्तदाता नेटवर्क',
    slide4Sub: '100% सुरक्षित, प्रमाणित और स्वैच्छिक रक्तदान शिविरों के साथ समुदायों को सशक्त बनाना।',

    // 4 Quick Service Cards
    becomeDonor: 'रक्तदाता बनें',
    becomeDonorDesc: 'हमारे मिशन में शामिल हों और अनगिनत जानें बचाएं।',
    registerNow: 'अभी रजिस्टर करें',
    checkEligibilityCardDesc: 'अपनी स्वास्थ्य और रक्तदान पात्रता तुरंत जांचें।',
    checkNow: 'जांचें',
    contactUsCardDesc: 'आपत्कालीन सहायता और प्रश्नों के लिए 24/7 संपर्क करें।',
    contactNow: 'संपर्क करें',
    contactUs: 'संपर्क करें',
    requestBloodTitle: 'रक्त अनुरोध करें',
    requestBloodDesc: 'रक्त की आवश्यकता है? अनुरोध सबमिट करें, हम मदद करेंगे।',
    requestNow: 'अभी अनुरोध करें',
    findBlood: 'रक्त खोजें',
    findBloodDesc: 'अपने क्षेत्र में रक्त की उपलब्धता खोजें।',
    searchNow: 'अभी खोजें',
    campsTitle: 'रक्तदान शिविर',
    campsDesc: 'आगामी रक्तदान शिविर खोजें और शामिल हों।',
    viewCamps: 'शिविर देखें',

    // Key Statistics
    happyDonors: 'संतुष्ट रक्तदाता',
    unitsDonated: 'डोनेट की गई इकाइयां',
    partnerHospitals: 'संबद्ध अस्पताल',
    campsCount: 'रक्तदान शिविर',

    // About Section on Home
    aboutUsBadge: 'हमारे बारे में',
    aboutUsTitle: 'हम जीवन बचाने के लिए समर्पित हैं',
    aboutUsDesc: 'ब्लड ट्रस्ट एक गैर-लाभकारी संगठन है जो रक्तदाताओं और जरूरतमंदों के बीच की दूरी को कम करने के लिए काम कर रहा है।',
    knowMoreAboutUs: 'हमारे बारे में और जानें',
    safeSecure: 'सुरक्षित और विश्वसनीय',
    safeSecureDesc: '100% सुरक्षित रक्तदान सुनिश्चित करने के लिए हम कड़े नियमों का पालन करते हैं।',
    trustedNetwork: 'विश्वसनीय नेटवर्क',
    trustedNetworkDesc: 'प्रमाणित ब्लड बैंकों और अस्पतालों से जुड़ा हुआ।',
    support247: '24/7 सहायता',
    support247Desc: 'हम आपकी मदद के लिए हमेशा तत्पर हैं।',

    // Vision & Mission Section
    ourPurpose: 'हमारा उद्देश्य और मूल मूल्य',
    ourVisionMission: 'हमारा विजन और मिशन',
    ourVisionMissionDesc: 'सुरक्षित, आत्मनिर्भर स्वैच्छिक रक्तदाता समुदाय के निर्माण के लिए समर्पित।',
    ourVision: 'हमारा विजन',
    visionTitle: 'रक्त की कमी से कोई जान न जाए',
    visionDesc: 'देश भर में 100% स्वैच्छिक, डिजिटल रूप से जुड़े रक्तदाता नेटवर्क का निर्माण करना जहां किसी भी मरीज को रक्त की कमी का सामना न करना पड़े।',
    visionPoint1: '100% स्वैच्छिक रक्तदाता समुदाय',
    visionPoint2: 'क्षेत्रीय अस्पतालों से त्वरित जुड़ाव',
    visionPoint3: 'पारदर्शी और सुरक्षित स्वास्थ्य नियम',
    ourMission: 'हमारा मिशन',
    missionTitle: 'रक्तदाताओं को प्रेरित करना और समाज को सशक्त बनाना',
    missionDesc: 'नागरिकों को सुलभ रक्तदान साधनों से सशक्त बनाना, नियमित रक्तदान शिविर आयोजित करना और आपात स्थिति में इच्छुक रक्तदाताओं को अस्पतालों से जोड़ना।',
    missionPoint1: 'सत्यापित डिजिटल जीवनरक्षक रजिस्टर',
    missionPoint2: 'सामुदायिक एवं कॉर्पोरेट रक्तदान शिविर',
    missionPoint3: '24/7 त्वरित जीवनरक्षक सहायता',

    // Who Can Donate Section
    whoCanDonate: 'रक्तदान कौन कर सकता है?',
    whoCanDonateDesc: 'रक्तदान एक सरल, सुरक्षित और जीवन रक्षक कार्य है। अपनी स्वास्थ्य पात्रता की जांच नीचे करें।',
    whoCanDonateText2: 'सामान्य मानदंडों के आधार पर स्वास्थ्य प्रतिशत का आकलन करने के लिए एक प्रश्नावली प्रदान की गई है।',
    findNearbyCamps: 'पास के शिविर खोजें',

    // Blood Camps Section
    upcomingBloodCamps: 'आगामी रक्तदान शिविर',
    viewAllCamps: 'सभी शिविर देखें',
    organizeCamp: 'शिविर आयोजित करें',
    bookCampSlot: 'शिविर स्लॉट बुक करें',

    // Testimonials
    whatDonorsSay: 'रक्तदाताओं का क्या कहना है',
    testimonial1: 'रक्तदान करना मेरा सबसे अच्छा निर्णय था। यह जानकर बहुत अच्छा लगा कि मैं एक जीवन बचा सकता हूँ।',
    testimonial2: 'प्रक्रिया बहुत ही सरल थी और टीम बहुत ही सहायक थी। अत्यधिक अनुशंसित!',
    testimonial3: 'दयालुता का एक छोटा सा कार्य बड़ा बदलाव ला सकता है। नियमित रक्तदाता होने पर गर्व है।',

    // Gallery Page
    ourGallery: 'हमारी मीडिया और समाचार गैलरी',
    gallerySub: 'हमारे स्वैच्छिक रक्तदान अभियानों और दुर्लभ बॉम्बे ब्लड ग्रुप पहलों के प्रमाणिक समाचार पत्र कतरन, राज्यपाल सम्मान और राष्ट्रीय पुरस्कार।',
    allMedia: 'सभी समाचार कतरन',
    photos: 'अखबार कतरन',
    videos: 'वीडियो',
    camps: 'रक्तदान अभियान',
    awareness: 'दुर्लभ बॉम्बे ग्रुप',
    awards: 'राज्य और राष्ट्रीय पुरस्कार',
    searchGallery: 'समाचार गैलरी खोजें...',
    mediaPhotoBadge: 'अखबार कतरन',
    mediaVideoBadge: 'वीडियो',

    // Real Press & Newspaper Clippings (Total: 20 Items)
    gItem1Title: 'आप्पासाहेब घोरपडे राष्ट्रीय पुरस्कार से सम्मानित',
    gItem1Sub: 'स्वैच्छिक रक्तदान में उत्कृष्ट योगदान के लिए आदर्श ब्लड डोनर 2021 पुरस्कार से सम्मानित।',
    
    gItem2Title: 'दुर्लभ बॉम्बे ब्लड ग्रुप के 50+ रक्तदान का मील का पत्थर',
    gItem2Sub: 'विक्रम यादव ने अत्यंत दुर्लभ बॉम्बे ब्लड ग्रुप का 54 से अधिक बार स्वैच्छिक रक्तदान किया।',
    
    gItem3Title: 'माननीय राज्यपाल भगत सिंह कोश्यारी द्वारा सम्मान',
    gItem3Sub: 'कोविड-19 महामारी के दौरान उत्कृष्ट जीवनरक्षक सामाजिक सेवा के लिए राजभवन में सम्मानित।',
    
    gItem4Title: 'बॉम्बे ओ ग्रुप को कर्तव्यदक्ष पुरस्कार प्रदान',
    gItem4Sub: 'ग्राहक पंचायत द्वारा उत्कृष्ट स्वैच्छिक रक्तदान सेवाओं के लिए सम्मानित।',
    
    gItem5Title: 'सिंधुदुर्ग में 66वां दुर्लभ बॉम्बे ब्लड ग्रुप रक्तदान',
    gItem5Sub: 'आपात स्थिति में सिंधुदुर्ग पहुँचकर दुर्लभ बॉम्बे ब्लड ग्रुप का रक्तदान कर जान बचाई।',

    gItem6Title: 'विक्रम यादव भारत के 179 दुर्लभ बॉम्बे ब्लड ग्रुप दाताओं में से एक',
    gItem6Sub: 'सकाल प्रेस रिपोर्ट: दुर्लभ बॉम्बे ब्लड ग्रुप के 50+ रक्तदान का कीर्तिमान स्थापित कर 22 राज्यों में 570 शाखाओं का नेटवर्क बनाया।',

    gItem7Title: '22 भारतीय राज्यों में दुर्लभ बॉम्बे ब्लड ग्रुप की आपूर्ति',
    gItem7Sub: 'तरुण भारत विशेष: विक्रम यादव के नेटवर्क द्वारा 22 राज्यों की 570 शाखाओं के माध्यम से दुर्लभ बॉम्बे ब्लड ग्रुप की आपूर्ति।',

    gItem8Title: 'बॉम्बे ब्लड ग्रुप का कार्य प्रेरणादायी: डॉ. मनोज इंगले',
    gItem8Sub: 'पुढारी प्रेस रिपोर्ट: तासगांव में आयोजित राष्ट्रीय पुरस्कार समारोह में 22 राज्यों की 45 संस्थाओं और 5 अंतरराष्ट्रीय गैर-सरकारी संगठनों का सम्मान।',

    gItem9Title: 'सांगली जिले में रक्त की कमी जागरूकता अभियान',
    gItem9Sub: 'लोकमत रिपोर्ट: भीषण गर्मी के दौरान ब्लड बैंकों में रक्त की कमी को दूर करने के लिए स्वैच्छिक रक्तदाताओं का विशेष अभियान।',

    gItem10Title: 'वे लोग जिनकी रगों में सोना बहता है - दुर्लभ बॉम्बे ब्लड दाता',
    gItem10Sub: 'मिड-डे विशेष रिपोर्ट (सी वाई गोपीनाथ): दुर्लभ बॉम्बे ब्लड दाताओं का सम्मान जो अनजान मरीजों की जान बचाने के लिए पूरे देश में यात्रा करते हैं।',

    gItem11Title: 'कर्नाटक के बच्चे की जान बचाने के लिए महाराष्ट्र के रक्तदाता पहुँचे',
    gItem11Sub: 'लोकमत मुख्य पृष्ठ रिपोर्ट: बीजापुर (कर्नाटक) में 1 वर्षीय बच्चे के ऑपरेशन के लिए विक्रम यादव ग्रुप द्वारा आपातकालीन बॉम्बे ब्लड रक्तदान।',

    gItem12Title: 'कर्नाटक के बच्चे के लिए महाराष्ट्र और कोंकण के रक्तदाता पहुँचे',
    gItem12Sub: 'बंधुता न्यूज रिपोर्ट: बामनेश्वर (कर्नाटक) में 1 वर्षीय बच्चे के ऑपरेशन के लिए ओंकार धनवड़े (दापोली) और हनुमंत भोसले (सांगली) द्वारा दुर्लभ बॉम्बे ब्लड रक्तदान।',

    gItem13Title: 'मदद का जज्बा खून में ही - जीवनरक्षक विक्रम यादव की कहानी',
    gItem13Sub: 'विशेष रिपोर्ट: विक्रम यादव द्वारा 68 से अधिक बार स्वैच्छिक रक्तदान और झारखंड, दिल्ली, आगरा, केरल, हैदराबाद में जीवनरक्षक यात्राएं।',

    gItem14Title: 'कोल्हापुर से हैदराबाद मरीज के लिए हवाई जहाज से भेजा गया दुर्लभ बॉम्बे ब्लड',
    gItem14Sub: 'सकाल मुख्य पृष्ठ रिपोर्ट: अपोलो अस्पताल हैदराबाद में 61 वर्षीय हृदय रोगी के ऑपरेशन के लिए कोल्हापुर से फ्लाइट द्वारा भेजा गया दुर्लभ बॉम्बे ब्लड।',

    gItem15Title: 'कवठेपिरान में विशाल रक्तदान शिविर संपन्न',
    gItem15Sub: 'आधुनिक केसरी न्यूज: बॉम्बे ब्लड ग्रुप और हिंद केसरी क्लब द्वारा आयोजित शिविर में 85 यूनिट रक्त एकत्र किया गया।',

    gItem16Title: 'विक्रम यादव को झारखंड में राष्ट्रीय पुरस्कार से सम्मानित किया गया',
    gItem16Sub: 'आधुनिक केसरी न्यूज: धनबाद (झारखंड) में रोटी ब्लड यूथ क्लब द्वारा विक्रम यादव को 69+ रक्तदान के लिए राष्ट्रीय पुरस्कार से नवाजा गया।',

    gItem17Title: 'बॉम्बे ब्लड ग्रुप मरीजों के लिए जीवनरक्षक देवदूत साबित हुआ',
    gItem17Sub: 'तरुण भारत रिपोर्ट: बीजापुर (कर्नाटक) अस्पताल के मरीज अयुम कारबा के लिए विक्रम यादव और टीम द्वारा आपातकालीन बॉम्बे ब्लड रक्तदान।',

    gItem18Title: 'विक्रम यादव के प्रयासों से सांगली जिला बना स्वैच्छिक रक्तदाता हब',
    gItem18Sub: 'विशेष समाचार: भारती अस्पताल मिरज में दुर्लभ बॉम्बे ब्लड ग्रुप का आपातकालीन रक्तदान कर मरीज को नया जीवन दिया।',

    gItem19Title: 'एक ही दिन में सबसे दुर्लभ बॉम्बे ब्लड की 5 थैलियों की आपूर्ति',
    gItem19Sub: 'लोकमत मस्ट रीड: दिल्ली, रायपुर, सोलापुर, पुणे और मुंबई के अस्पतालों में एक साथ 5 बॉम्बे ब्लड यूनिट भेजकर नया रिकॉर्ड बनाया।',

    gItem20Title: 'बॉम्बे ब्लड ग्रुप तासगांव संस्था को महाराष्ट्र गौरव सम्मान से सम्मानित किया गया',
    gItem20Sub: 'ईगल न्यूज रिपोर्ट: मालाड (मुंबई) में आयोजित समारोह में विक्रम यादव एवं टीम को श्री छत्रपति शिवाजी महाराज महाराष्ट्र गौरव सम्मान प्रदान किया गया।',

    // Form Field Labels (Register / Login / Contact)
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    phoneNumber: 'फोन नंबर',
    password: 'पासवर्ड',
    bloodGroup: 'रक्त समूह',
    cityRegion: 'शहर / क्षेत्र',
    weightKg: 'वजन (किग्रा)',
    rarePhenotypeCheck: 'यदि आप दुर्लभ रक्त समूह (जैसे बॉम्बे ब्लड, Rh-null) से हैं तो यहाँ टिक करें।',
    donorRegistrationTitle: 'रक्तदाता पंजीकरण',
    donorRegistrationSub: 'जीवनरक्षक नेटवर्क से जुड़ें। इसमें 2 मिनट से भी कम समय लगता है।',

    // Page Specific Headers
    availabilityPageTitle: 'रियल-टाइम रक्त उपलब्धता और इन्वेंटरी',
    availabilityPageDesc: 'प्रमाणित डिपो, क्षेत्रीय ब्लड बैंकों और अस्पतालों में लाइव ब्लड स्टॉक खोजें।',
    directoryPageTitle: 'ब्लड बैंक और अस्पताल निर्देशिका',
    directoryPageDesc: 'इंटरैक्टिव गूगल मैप्स और रीयल-टाइम संपर्क विवरण के साथ ब्लड बैंकों को खोजें।',
    contactPageTitle: 'हमारी आपातकालीन हेल्पलाइन से संपर्क करें',
    contactPageDesc: 'कोई प्रश्न हैं या आपातकालीन सहायता की आवश्यकता है? हमारी 24/7 सहायता टीम से संपर्क करें।',
    galleryPageTitle: 'ब्लड ट्रस्ट मीडिया और समाचार आर्काइव्स',

    // Auth Pages
    welcomeBack: 'पुनः स्वागत है',
    loginAccount: 'अपने खाते में लॉगिन करें',
    createDonorAccount: 'नया रक्तदाता खाता बनाएं',
    loginBtn: 'खाते में लॉगिन करें',
    registerBtn: 'जीवनरक्षक के रूप में पंजीकरण करें',

    // Admin Dashboard Translations
    adminPortalTitle: 'एडमिन पोर्टल',
    overview: 'अवलोकन',
    donorManagement: 'रक्तदाता प्रबंधन',
    whatWeDo: 'हम क्या करते हैं',
    settings: 'सेटिंग्स',
    support: 'सहायता',
    registerNewDonor: 'नया रक्तदाता पंजीकृत करें',
    adminOverviewTitle: 'ब्लड ट्रस्ट एडमिन अवलोकन',
    adminOverviewSub: 'स्वैच्छिक रक्तदाता नेटवर्क और सामुदायिक संचालन का उच्च-स्तरीय सारांश।',
    totalDonors: 'कुल पंजीकृत रक्तदाता',
    eligibleDonors: 'पात्र रक्तदाता',
    campsOrganized: 'आयोजित रक्तदान शिविर',
    connectedHospitals: 'संबद्ध अस्पताल',
    searchDonorsPlaceholder: 'रक्तदाता, आईडी, संपर्क खोजें...',
    donorId: 'दाता आईडी',
    donorName: 'दाता का नाम',
    lastDonation: 'अंतिम रक्तदान',
    status: 'स्थिति',
    actions: 'कार्रवाई',
    recentRegistrations: 'हाल के रक्तदाता पंजीकरण',
    viewAllDonors: 'सभी रक्तदाता देखें',

    // Admin CMS Tab Translations
    pageCms: 'पेज टेक्स्ट और इमेज CMS',
    cmsTitle: 'वेबसाइट टेक्स्ट और इमेज CMS',
    cmsDesc: 'पूरे वेबसाइट पर शीर्षक, विवरण, आंकड़े और इमेज लिंक बदलें।',
    resetDefaults: 'डिफ़ॉल्ट रीसेट करें',
    subTabHero: 'हीरो बैनर स्लाइडर',
    subTabVision: 'विजन और मिशन',
    subTabAbout: 'हमारे बारे में',
    subTabStats: 'मुख्य आंकड़े',
    subTabGallery: 'मीडिया गैलरी आइटम',
    heroSlidesTitle: 'हीरो बैनर स्लाइड',
    heroSlidesSub: 'होमपेज पर दिखने वाले बैनर स्लाइड जोड़ें, संपादित करें या हटाएं।',
    addNewSlide: '+ नई स्लाइड जोड़ें',
    saveSlides: 'स्लाइड सहेजें',
    imageUrlLabel: 'इमेज URL / फाइल पाथ',
    titlePrefixLabel: 'शीर्षक उपसर्ग (पंक्ति 1)',
    highlightWordLabel: 'हाईलाइट शब्द',
    subtitleLabel: 'उपशीर्षक / विवरण',
    vmSectionTitle: 'विजन और मिशन सेक्शन टेक्स्ट',
    vmSectionSub: 'शीर्षक, विवरण और मुख्य बिंदु संपादित करें।',
    saveVm: 'विजन और मिशन सहेजें',
    aboutUsCmsTitle: 'हमारे बारे में सेक्शन',
    aboutUsCmsSub: 'होमपेज "हमारे बारे में" सेक्शन का शीर्षक और विवरण संपादित करें।',
    saveAboutUs: 'हमारे बारे में सहेजें',
    sectionBadgeTag: 'सेक्शन बैज टैग',
    mainTitleLabel: 'मुख्य शीर्षक',
    mainDescLabel: 'मुख्य विवरण पाठ',
    keyStatsCmsTitle: 'मुख्य प्रभाव आंकड़े',
    keyStatsCmsSub: 'रक्तदाता संख्या, दान की गई इकाइयां, संबद्ध अस्पताल और शिविर संख्या संपादित करें।',
    saveStats: 'आंकड़े सहेजें',
    labelHappyDonors: 'पंजीकृत संतुष्ट रक्तदाता',
    labelUnitsDonated: 'दान की गई रक्त इकाइयां',
    labelPartnerHospitals: 'संबद्ध अस्पताल',
    labelCampsCount: 'आयोजित रक्तदान शिविर',
    galleryCmsTitle: 'मीडिया गैलरी आइटम',
    galleryCmsSub: 'नई अखबार कतरन जोड़ें, शीर्षक/उपशीर्षक संपादित करें या हटाएं।',
    addNewNewspaperItem: '+ अखबार आइटम जोड़ें',
    saveGalleryItems: 'गैलरी आइटम सहेजें',
    headlineTitleLabel: 'हेडलाइन / शीर्षक',
    subtextSummaryLabel: 'उपशीर्षक / सारांश',
    dateLabel: 'दिनांक',
    locationSourceLabel: 'स्थान / स्रोत',
    subTabContact: 'संपर्क जानकारी',
    subTabOther: 'पात्रता और शिविर पेज',
    contactCmsTitle: 'संपर्क पेज जानकारी',
    contactCmsSub: 'आपातकालीन हेल्पलाइन नंबर, ईमेल, मुख्यालय का पता और विवरण संपादित करें।',
    emergencyLineLabel: '24/7 आपातकालीन हेल्पलाइन / फोन',
    emailInquiryLabel: 'सामान्य ईमेल पूछताछ',
    headquartersLabel: 'मुख्यालय का पता',
    contactDescLabel: 'संपर्क जानकारी विवरण',
    otherCmsTitle: 'पात्रता मानदंड और रक्तदान शिविर CMS',
    otherCmsSub: 'पब्लिक पेजों पर प्रदर्शित उपशीर्षक और पात्रता दिशानिर्देश संपादित करें।',
    campsSubtitleLabel: 'रक्तदान शिविर पेज उपशीर्षक',
    eligSubtitleLabel: 'पात्रता पेज उपशीर्षक',
    ageDescLabel: 'आयु सीमा विवरण',
    weightDescLabel: 'वजन आवश्यकता विवरण',
    hemoDescLabel: 'हीमोग्लोबिन स्तर विवरण',
    intervalDescLabel: 'रक्तदान अंतराल विवरण',
    saveContact: 'संपर्क जानकारी सहेजें',
    saveOther: 'पेज दिशानिर्देश सहेजें',
    subTabAboutPage: 'हमारे बारे में पेज CMS',
    subTabDonatePage: 'रक्तदान पेज CMS',
    subTabGalleryPage: 'मीडिया गैलरी पेज CMS',
    aboutPageCmsTitle: 'हमारे बारे में पेज कंटेंट व कार्ड आंकड़े',
    aboutPageCmsSub: 'शीर्षक, उपशीर्षक, उद्देश्य व कार्ड आंकड़े संपादित करें या नए जोड़ें।',
    addNewStatCard: '+ नया कार्ड जोड़ें',
    saveAboutPage: 'हमारे बारे में पेज सहेजें',
    donateCmsTitle: 'रक्तदान पेज हेडर',
    donateCmsSub: 'रक्तदाता पंजीकरण पेज का शीर्षक और उपशीर्षक संपादित करें।',
    saveDonate: 'रक्तदान पेज सहेजें',
    galleryHeaderCmsTitle: 'गैलरी पेज बैनर व कतरनें',
    galleryHeaderCmsSub: 'शीर्षक, उपशीर्षक, बैज टैग और अखबार कतरनें संपादित करें।',
    badgeLabel: 'बैज / टैग लाइन',
    statValueLabel: 'आंकड़ा मान (उदा. 100%, 200+, Zero)',
    statLabelText: 'कार्ड लेबल टेक्स्ट',
    aboutPageTitle: 'हमारे बारे में',
    aboutPageSubtitle: 'ब्लड ट्रस्ट एक गैर-लाभकारी स्वैच्छिक रक्तदाता नेटवर्क है जो इच्छुक दाताओं को प्रमाणित अस्पतालों से जोड़ता है।',
    aboutPagePurposeTitle: 'हमारा उद्देश्य और मुख्य मूल्य',
    aboutPagePurposeDesc1: 'देश भर में 100% स्वैच्छिक, डिजिटल रूप से सिंक्रनाइज़ रक्तदाता नेटवर्क का निर्माण करना जहां किसी भी आपत्कालीन रोगी को सुरक्षित, अनुकूलता वाले रक्त की अनुपलब्धता के कारण परेशानी न हो।',
    aboutPagePurposeDesc2: 'नागरिकों को सुलभ दाता उपकरणों से सशक्त बनाना, नियमित रक्तदान शिविरों का आयोजन करना, युवाओं को शिक्षित करना और गंभीर क्षणों में इच्छुक दाताओं को साझेदार स्वास्थ्य संस्थानों से जोड़ना।',
    zeroFees: 'शून्य व्यावसायिक शुल्क',
    isoCertified: 'आईएसओ प्रमाणित प्रोटोकॉल',

    // Additional Page & Component UI Translations
    ageLimit: 'आयु सीमा',
    ageLimitDesc: '18 से 65 वर्ष के बीच।',
    minWeight: 'न्यूनतम वजन',
    minWeightDesc: 'मानक 450ml रक्तदान के लिए कम से कम 50 किग्रा।',
    hemoglobinLevel: 'हीमोग्लोबिन स्तर',
    hemoglobinLevelDesc: 'रक्तदान से पहले परीक्षण में न्यूनतम 12.5 ग्राम/डीएल।',
    donationInterval: 'रक्तदान अंतराल',
    donationIntervalDesc: 'पुरुषों के लिए 90 दिन (3 महीने); महिलाओं के लिए 120 दिन (4 महीने)।',
    qAge: 'क्या आपकी आयु 18 से 65 वर्ष के बीच है?',
    qWeight: 'क्या आपका वजन कम से कम 50 किग्रा है?',
    qGap: 'क्या आपके पिछले रक्तदान को कम से कम 3 महीने हो चुके हैं?',
    eligibleSuccessTitle: 'प्राथमिक आकलन: पात्र',
    eligibleSuccessDesc: 'आप मानक स्वास्थ्य मानदंडों को पूरा करते हैं। जीवन बचाने के लिए पंजीकरण करें।',
    ineligibleTitle: 'प्राथमिक आकलन: अपात्र',
    ineligibleDesc: 'कृपया रक्तदान करने से पहले चिकित्सा दिशानिर्देशों की समीक्षा करें।',
    mediaRecognition: 'मीडिया पहचान व सम्मान',
    gallerySubtitle: 'बचाए गए जीवन। लौटाई गई उम्मीदें। हमारी प्रामाणिक अखबार कतरनें, पुरस्कार और प्रेस कवरेज देखें।',
    viewFullDetails: 'पूरा विवरण देखें',
    details: 'विवरण',
    pressClipping: 'अखबार कतरन',
    viewAllClippings: 'गैलरी में सभी 20 कतरनें देखें',
    emergencyLine: '24/7 आपत्कालीन हेल्पलाइन',
    emailInquiry: 'सामान्य ईमेल पूछताछ',
    headquarters: 'मुख्यालय',
    yourName: 'आपका नाम',
    yourEmail: 'आपका ईमेल',
    subject: 'विषय',
    message: 'संदेश',
    sendMessage: 'संदेश भेजें',
    messageSent: 'संदेश सफलतापूर्वक भेजा गया!',
    messageSentDesc: 'ब्लड ट्रस्ट से संपर्क करने के लिए धन्यवाद। हमारी टीम 24 घंटे के भीतर आपसे संपर्क करेगी।',
    sendAnother: 'दूसरा संदेश भेजें'
  },

  mr: {
    // Navbar & Footer
    home: 'मुखपृष्ठ',
    about: 'आमच्याबद्दल',
    donate: 'रक्तदान करा',
    requestBlood: 'रक्त मागणी',
    trackRequests: 'मागणी आढावा',
    bloodCamps: 'रक्तदान शिबीर',
    volunteers: 'स्वयंसेवक',
    gallery: 'गॅलरी',
    contact: 'संपर्क साधा',
    loginRegister: 'लॉगिन / नोंदणी',
    portal: 'पोर्टल',
    logout: 'लॉगआउट',
    tagline: 'रक्तदान करा, जीवन वाचवा',
    selectLanguage: 'भाषा निवडा',
    english: 'English',
    hindi: 'हिंदी (Hindi)',
    marathi: 'मराठी (Marathi)',
    quickLinks: 'महत्त्वाच्या लिंक्स',
    contactInfo: 'संपर्क माहिती',
    allRightsReserved: 'सर्व हक्क राखीव.',
    footerDesc: 'ब्लड ट्रस्ट हे स्वयंच्छिक रक्तदात्यांना प्रमाणित रुग्णालयांशी जोडणारे बिनफासटी नेटवर्क आहे.',

    // Hero Section
    heroBadge: 'आणीबाणी रक्तदान नेटवर्क',
    heroTitleLine1: 'एक रक्तदान',
    heroTitleLine2: 'अनेक ',
    heroTitleHighlight: 'जीव वाचवू शकते',
    heroSubtitle: 'हिरो बना. रक्तदान करा आणि कोणाच्या तरी आयुष्यात बदल घडवा.',
    donateNow: 'आता रक्तदान करा',
    learnMore: 'अधिक माहिती',
    findBloodStock: 'रक्त साठा शोधा',
    emergencyRequest: 'आपत्कालीन मागणी',
    viewCampSchedule: 'शिबीर वेळापत्रक',
    registerAsDonor: 'रक्तदाता नोंदणी',
    checkEligibility: 'पात्रता तपासा',
    donorFAQ: 'सतत विचारले जाणारे प्रश्न',
    viewGallery: 'गॅलरी पहा',

    // Hero Slider Translations
    slide1Title1: 'बॉम्बे ब्लड ग्रुप संस्था',
    slide1Title2: 'राष्ट्रीय ',
    slide1Highlight: 'पुरस्कार सोहळा',
    slide1Sub: 'स्वयंच्छिक रक्तदान आणि जीवनदायी सामाजिक सेवेतील उत्कृष्टतेचा गौरव.',

    slide2Title1: 'रुपये राज्यपालांकडून सत्कार',
    slide2Title2: 'निस्वार्थ सेवेसाठी ',
    slide2Highlight: 'सन्मानित',
    slide2Sub: 'महाराष्ट्राचे माननीय राज्यपाल भगतसिंग कोश्यारी यांच्या हस्ते उत्कृष्ट सामाजिक कार्याबद्दल सन्मानित.',

    slide3Title1: 'राष्ट्रीय पुरस्कार 2018',
    slide3Title2: 'एकत्रितपणे ',
    slide3Highlight: 'जीव वाचवत',
    slide3Sub: 'राष्ट्रीय पुरस्कार सोहळ्यात सन्मानित स्वयंच्छिक रक्तदाते आणि आयोजकांचा गौरव.',

    slide4Title1: 'प्रत्येक थेंब मोलाचा',
    slide4Title2: 'आमचे समर्पित ',
    slide4Highlight: 'रक्तदाता नेटवर्क',
    slide4Sub: '१००% सुरक्षित, प्रमाणित आणि स्वयंच्छिक रक्तदान शिबिरांद्वारे समाजाला सक्षम करणे.',

    // 4 Quick Service Cards
    becomeDonor: 'रक्तदाता बना',
    becomeDonorDesc: 'आमच्या मोहिमेत सामील व्हा आणि अगणित जीव वाचवा.',
    registerNow: 'आता नोंदणी करा',
    checkEligibilityCardDesc: 'तुमची आरोग्य व रक्तदान पात्रता त्वरित तपासा.',
    checkNow: 'तपासा',
    contactUsCardDesc: 'आपत्कालीन मदत व चौकशीसाठी २४/७ संपर्क साधा.',
    contactNow: 'संपर्क साधा',
    contactUs: 'संपर्क साधा',
    requestBloodTitle: 'रक्त मागणी करा',
    requestBloodDesc: 'रक्ताची गरज आहे? मागणी नोंदवा, आम्ही मदत करू.',
    requestNow: 'आता मागणी करा',
    findBlood: 'रक्त शोधा',
    findBloodDesc: 'आपल्या परिसरातील उपलब्ध रक्त साठा शोधा.',
    searchNow: 'आता शोधा',
    campsTitle: 'रक्तदान शिबीर',
    campsDesc: 'आगामी रक्तदान शिबिरे शोधा आणि सहभागी व्हा.',
    viewCamps: 'शिबिरे पहा',

    // Key Statistics
    happyDonors: 'आनंदी रक्तदाते',
    unitsDonated: 'दान केलेले युनिट्स',
    partnerHospitals: 'संलग्न रुग्णालये',
    campsCount: 'रक्तदान शिबीर',

    // About Section on Home
    aboutUsBadge: 'आमच्याबद्दल',
    aboutUsTitle: 'आम्ही जीवन वाचवण्यासाठी तत्पर आहोत',
    aboutUsDesc: 'ब्लड ट्रस्ट ही एक बिगर-नफा संस्था आहे जी रक्तदाते आणि गरजू रुग्णांमधील अंतर भरून काढण्यासाठी कार्यरत आहे.',
    knowMoreAboutUs: 'आमच्याबद्दल अधिक जाणून घ्या',
    safeSecure: 'सुरक्षित आणि विश्वासार्ह',
    safeSecureDesc: '१००% सुरक्षित रक्तदान सुनिश्चित करण्यासाठी आम्ही कडक नियमांचे पालन करतो.',
    trustedNetwork: 'विश्वासू नेटवर्क',
    trustedNetworkDesc: 'प्रमाणित रक्तपेढ्या आणि रुग्णालयांशी जोडलेले.',
    support247: '२४/७ मदत',
    support247Desc: 'आम्ही तुम्हाला मदत करण्यासाठी नेहमीच तयार आहोत.',

    // Vision & Mission Section
    ourPurpose: 'आमचे उद्दिष्ट आणि मूल्ये',
    ourVisionMission: 'आमचे व्हिजन आणि मिशन',
    ourVisionMissionDesc: 'सुरक्षित आणि स्वयंपूर्ण स्वयंच्छिक रक्तदाता समुदाय उभारण्यासाठी कटिबद्ध.',
    ourVision: 'आमचे व्हिजन',
    visionTitle: 'रक्ताच्या तुटवड्यामुळे एकही प्राण जाणार नाही',
    visionDesc: 'देशभरात १००% स्वयंच्छिक रक्तदाता नेटवर्क तयार करणे जेणेकरून कोणत्याही आपत्कालीन रुग्णाला वेळेवर रक्त मिळेल.',
    visionPoint1: '१००% स्वयंच्छिक रक्तदाता समुदाय',
    visionPoint2: 'क्षेत्रीय रुग्णालयांशी थेट संपर्क',
    visionPoint3: 'पारदर्शक आणि सुरक्षित आरोग्य नियम',
    ourMission: 'आमचे मिशन',
    missionTitle: 'रक्तदात्यांना प्रेरित करणे व समाजाला सक्षम करणे',
    missionDesc: 'नागरिकांना सोप्या साधनांद्वारे सक्षम करणे, नियमित रक्तदान शिबिरे आयोजित करणे आणि गरजू रुग्णांना रक्तदात्यांशी जोडणे.',
    missionPoint1: 'सत्यापित डिजिटल जीवनरक्षक नोंदणी',
    missionPoint2: 'सामाजिक व कॉर्पोरेट रक्तदान शिबिरे',
    missionPoint3: '२४/७ तातडीची जीवनरक्षक मदत',

    // Who Can Donate Section
    whoCanDonate: 'रक्तदान कोण करू शकते?',
    whoCanDonateDesc: 'रक्तदान हे अत्यंत सोपे, सुरक्षित आणि जीवनदायी कार्य आहे. आपली पात्रता खाली तपासा.',
    whoCanDonateText2: 'सामान्य निकषांच्या आधारे आरोग्य टक्केवारीचे मूल्यांकन करण्यासाठी एक प्रश्नावली दिली आहे.',
    findNearbyCamps: 'जवळची शिबिरे शोधा',

    // Blood Camps Section
    upcomingBloodCamps: 'आगामी रक्तदान शिबिरे',
    viewAllCamps: 'सर्व शिबिरे पहा',
    organizeCamp: 'शिबीर आयोजित करा',
    bookCampSlot: 'शिबीर स्लॉट बुक करा',

    // Testimonials
    whatDonorsSay: 'रक्तदाते काय म्हणतात',
    testimonial1: 'रक्तदान करण्याचा निर्णय माझा सर्वोत्तम होता. मी कोणाचे तरी प्राण वाचवू शकलो हे जाणून आनंद झाला.',
    testimonial2: 'प्रक्रिया खूप सोपी होती आणि टीम खूप मदत करणारी होती. अत्यंत शिफारस करतो!',
    testimonial3: 'दयाळूपणाची छोटीशी कृती मोठा बदल घडवू शकते. नियमित रक्तदाता असल्याचा सार्थ अभिमान आहे.',

    // Gallery Page
    ourGallery: 'आमची वृत्तपत्र व मीडिया गॅलरी',
    gallerySub: 'आमच्या स्वयंच्छिक रक्तदान मोहिमा आणि दुर्मिळ बॉम्बे ब्लड ग्रुप उपक्रमांची वृत्तपत्रे, राज्यपाल सत्कार आणि राष्ट्रीय गौरव पुरस्कार.',
    allMedia: 'सर्व बातमी कत्रणे',
    photos: 'वृत्तपत्र कत्रणे',
    videos: 'व्हिडिओ',
    camps: 'रक्तदान मोहिमा',
    awareness: 'दुर्मिळ बॉम्बे ग्रुप',
    awards: 'राज्य व राष्ट्रीय पुरस्कार',
    searchGallery: 'गॅलरी शोधा...',
    mediaPhotoBadge: 'वृत्तपत्र बातमी',
    mediaVideoBadge: 'व्हिडिओ',

    // Real Press & Newspaper Clippings (Total: 20 Items)
    gItem1Title: 'आप्पासाहेब घोरपडे राष्ट्रीय पुरस्काराने सन्मानित',
    gItem1Sub: 'रक्तदान क्षेत्रातील उत्कृष्ट कामगिरीबद्दल बॉम्बे ब्लड ग्रुपकडून आदर्श ब्लड डोनर २०२१ पुरस्काराने सन्मानित.',
    
    gItem2Title: 'दुर्मीळ बॉम्बे ब्लड ग्रुपच्या दानाची पन्नाशी',
    gItem2Sub: 'विक्रम यादव यांनी ५४ पेक्षा जास्त वेळा दुर्मीळ बॉम्बे ब्लड ग्रुपचे रक्तदान करून हजारो रुग्णांचे प्राण वाचवले.',
    
    gItem3Title: 'तासगावच्या बॉम्बे ब्लडचा राज्यपालांच्याहस्ते गौरव',
    gItem3Sub: 'कोविड काळात केलेल्या उत्कृष्ट जीवनरक्षक कार्याबद्दल राज्यपाल भगतसिंग कोश्यारी यांच्याहस्ते सन्मान.',
    
    gItem4Title: 'तासगावच्या बॉम्बे ओ ला कर्तव्यदक्ष पुरस्कार प्रदान',
    gItem4Sub: 'ग्राहक पंचायतीच्यावतीने विद्याधर अनास्कर यांच्याहस्ते कर्तव्यदक्ष सेवा गौरव पुरस्काराने सन्मानित.',
    
    gItem5Title: 'सिंधुदुर्गात ६६ वे दुर्मीळ बॉम्बे ब्लड रक्तदान',
    gItem5Sub: 'अत्यंत बिकट प्रसंगी धावून जाऊन ६६ व्या दुर्मीळ बॉम्बे ब्लड ग्रुपचे रक्तदान करून रुग्णाला जीवनदान.',

    gItem6Title: 'विक्रम यादव भारतातील १७९ जणांपैकी एक; रक्तादानाची चळवळ जोमात',
    gItem6Sub: 'सकाळ वृत्तसेवा रिपोर्ट: दुर्मीळ बॉम्बे ब्लड ग्रुपच्या दानाची पन्नाशी पूर्ण करून २२ राज्यांमध्ये ५७० शाखांचे जाळे उभारून रुग्णांना विनामूल्य रक्त पुरवठा.',

    gItem7Title: 'दुर्मीळ बॉम्बे रक्तगटाचा २२ राज्यात पुरवठा',
    gItem7Sub: 'दै. तरुण भारत जागतिक रक्तदाता दिन विशेष: विक्रम यादव यांच्या नेटवर्कतर्फे २२ राज्यांमध्ये ५७० शाखांद्वारे दुर्मीळ बॉम्बे रक्तगटाचा पुरवठा.',

    gItem8Title: 'बॉम्बे ब्लड ग्रुपचे कार्य प्रेरणादायी : डॉ. मनोज इंगळकर',
    gItem8Sub: 'पुढारी बातमी पत्र: तासगाव येथे आयोजित राष्ट्रीय पुरस्कार वितरण सोहळ्यात देशातील २२ राज्यांमधील ४५ संस्था व ५ आंतरराष्ट्रीय स्वयंसेवी संस्थांचा गौरव.',

    gItem9Title: 'जिल्ह्यात रक्ताचा तुटवडा; रक्तदान जनजागृती मोहीम',
    gItem9Sub: 'लोकमत बातमी पत्र: सांगली जिल्ह्यातील रक्ताचा तुटवडा दूर करण्यासाठी स्वैच्छिक रक्तदात्यांना पुढे येण्याचे आग्रही आवाहन.',

    gItem10Title: 'वे लोक ज्यांच्या रक्तामध्ये सोनं वाहते - दुर्मीळ बॉम्बे ब्लड दाते',
    gItem10Sub: 'मिड-डे इंग्रजी विशेष लेख (सी वाय गोपीनाथ): अनोळखी रुग्णांचे प्राण वाचवण्यासाठी देशभर धाव घेणाऱ्या दुर्मीळ बॉम्बे ब्लड ग्रुप दात्यांचा गौरव.',

    gItem11Title: 'कर्नाटकच्या बाळाचा जीव वाचवण्यासाठी धावले महाराष्ट्रातील रक्तदाते',
    gItem11Sub: 'लोकमत पहिल्या पानावरील बातमी: विजापूर (कर्नाटक) येथील १ वर्षाच्या लहान बाळाच्या शस्त्रक्रियेसाठी विक्रम यादव यांच्या ग्रुपतर्फे धावून जात तातडीने बॉम्बे ब्लड रक्तदान.',

    gItem12Title: 'कर्नाटकच्या रूग्णासाठी महाराष्ट्र व कोकणातील रक्तदाते धावले',
    gItem12Sub: 'बंधुता न्यूज: कर्नाटक मधील बाबलेश्वर येथील १ वर्षीय लहान बाळाच्या ऑपरेशनसाठी ओंकार धनवडे (दापोली) व हनुमंत भोसले (कुची, सांगली) यांनी केले बॉम्बे ब्लड रक्तदान.',

    gItem13Title: 'मदतीची भावना रक्तातच - जीवनरक्षक विक्रम यादव यांची जीवनगाथा',
    gItem13Sub: 'विशेष बातमी पत्र: स्वतः ६८ पेक्षा जास्त वेळा रक्तदान करून झारखंड, दिल्ली, आग्रा, केरळ व हैदराबाद येथे धावून जात रुग्णांचे प्राण वाचवणारे विक्रम यादव.',

    gItem14Title: 'हैदराबादच्या रुग्णासाठी दुर्मीळ बॉम्बे ब्लड ग्रुपचे रक्त विमानाने पाठवले',
    gItem14Sub: 'दै. सकाळ पहिल्या पानावरील विशेष: हैदराबाद येथील ६१ वर्षीय हृदय शस्त्रक्रिया रुग्णासाठी कोल्हापूरहून विमानाने पाठवले दुर्मीळ बॉम्बे ब्लड.',

    gItem15Title: 'कवठेपिरानतर्फे भव्य रक्तदान शिबीर संपन्न',
    gItem15Sub: 'आधुनिक केसरी न्यूज: बॉम्बे ब्लड ग्रुप ऑर्गनायझर व हिंद केसरी क्लब मिरज यांच्या संयुक्त विद्यमाने आयोजित शिबिरात ८५ रक्तदात्यांनी केले रक्तदान.',

    gItem16Title: 'सांगलीच्या विक्रम यादव यांना झारखंड येथील राष्ट्रीय पुरस्कार',
    gItem16Sub: 'आधुनिक केसरी न्यूज: धनबाद (झारखंड) येथे आंतरराष्ट्रीय सन्मान सोहळ्यात रोटी ब्लड यूथ क्लबतर्फे विक्रम यादव यांना नॅशनल अवॉर्ड प्रदान.',

    gItem17Title: 'बॉम्बे ब्लड ग्रुप ठरले रुग्णासाठी देवदुत',
    gItem17Sub: 'दै. तरुण भारत संवाद: विजापूर (कर्नाटक) येथील अयुम कारबा या रुग्णासाठी विक्रम यादव, अतुल चौगुले व धीरज पाटील यांच्याकडून तातडीने बॉम्बे ब्लड रक्तदान.',

    gItem18Title: 'विक्रम यादव यांच्या प्रयत्नातून सांगली जिल्हा बनला रक्तदात्याचा जिल्हा',
    gItem18Sub: 'विलासराव कोलेकर बातमी पत्र: भारती हॉस्पिटल मिरज येथे दुर्मीळ बॉम्बे ब्लड ग्रुपचे तातडीचे रक्तदान करून रुग्णाला दिले जीवनदान.',

    gItem19Title: 'सर्वांत दुर्मीळ रक्त... तरीही एकाच दिवसात पुरविल्या ५ पिशव्या',
    gItem19Sub: 'लोकमत मस्ट रीड (१४ जून २०२६): दिल्ली, रायपूर, सोलापूर, पुणे व मुंबई येथील गंभीर रुग्णांसाठी एकाच दिवसात ५ दुर्मीळ बॉम्बे ब्लड पिशव्यांचा पुरवठा करून नवीन विक्रम.',

    gItem20Title: 'बॉम्बे ब्लड ग्रुप तासगाव संस्थेला महाराष्ट्र गौरव सन्मान प्रदान',
    gItem20Sub: 'ईगल न्यूज नेटवर्क: मालाड (मुंबई) येथे अरिहंतनायक रक्त सारथी संस्था राजस्थानतर्फे श्री छत्रपति शिवाजी महाराज महाराष्ट्र गौरव सन्मान सोहळ्यात अध्यक्ष विक्रम यादव व टीमचा विशेष सन्मान.',

    // Form Field Labels (Register / Login / Contact)
    fullName: 'पूर्ण नाव',
    emailAddress: 'ईमेल पत्ता',
    phoneNumber: 'फोन नंबर',
    password: 'पासवर्ड',
    bloodGroup: 'रक्तगट',
    cityRegion: 'शहर / भाग',
    weightKg: 'वजन (किग्रॅ)',
    rarePhenotypeCheck: 'तुम्ही दुर्मिळ रक्तगटातील (उदा. बॉम्बे ब्लड, Rh-null) असाल तर येथे टिक करा.',
    donorRegistrationTitle: 'रक्तदाता नोंदणी',
    donorRegistrationSub: 'जीवनरक्षक नेटवर्कमध्ये सामील व्हा. याला २ मिनिटांपेक्षा कमी वेळ लागतो.',

    // Page Specific Headers
    availabilityPageTitle: 'रिअल-टाईम रक्त उपलब्धता आणि साठा',
    availabilityPageDesc: 'प्रमाणित डिपो, प्रादेशिक रक्तपेढ्या आणि रुग्णालयांमध्ये थेट रक्त साठा शोधा.',
    directoryPageTitle: 'रक्तपेढी आणि रुग्णालय निर्देशिका',
    directoryPageDesc: 'गुगल मॅप्स आणि थेट संपर्क तपशीलासह प्रमाणित रक्तपेढ्या शोधा.',
    contactPageTitle: 'आमच्या आपत्कालीन हेल्पलाइनशी संपर्क साधा',
    contactPageDesc: 'काही प्रश्न आहेत किंवा आपत्कालीन मदतीची गरज आहे? आमच्या २४/७ सपोर्ट टीमशी संपर्क साधा.',
    galleryPageTitle: 'ब्लड ट्रस्ट वृत्तपत्र व मीडिया अर्काईव्हज',

    // Auth Pages
    welcomeBack: 'पुन्हा स्वागत आहे',
    loginAccount: 'आपल्या खात्यात लॉगिन करा',
    createDonorAccount: 'नवीन रक्तदाता खाते तयार करा',
    loginBtn: 'खात्यात लॉगिन करा',
    registerBtn: 'जीवनरक्षक म्हणून नोंदणी करा',

    // Admin Dashboard Translations
    adminPortalTitle: 'अ‍ॅडमिन पोर्टल',
    overview: 'आढावा',
    donorManagement: 'रक्तदाता व्यवस्थापन',
    whatWeDo: 'आम्ही काय करतो',
    settings: 'सेटिंग्ज',
    support: 'मदत व सपोर्ट',
    registerNewDonor: 'नवीन रक्तदात्याची नोंदणी करा',
    adminOverviewTitle: 'ब्लड ट्रस्ट अ‍ॅडमिन आढावा',
    adminOverviewSub: 'स्वैंच्छिक रक्तदाता नेटवर्क आणि सामाजिक कामांचा उच्चस्तरीय सारांश.',
    totalDonors: 'एकूण नोंदणीकृत रक्तदाते',
    eligibleDonors: 'पात्र रक्तदाते',
    campsOrganized: 'आयोजित रक्तदान शिबिरे',
    connectedHospitals: 'संलग्न रुग्णालये',
    searchDonorsPlaceholder: 'रक्तदाते, आयडी, संपर्क शोधा...',
    donorId: 'दाता आयडी',
    donorName: 'दात्याचे नाव',
    lastDonation: 'शेवटचे रक्तदान',
    status: 'स्थिती',
    actions: 'कृती',
    recentRegistrations: 'नुकतीच झालेली रक्तदाता नोंदणी',
    viewAllDonors: 'सर्व रक्तदाते पहा',

    // Admin CMS Tab Translations
    pageCms: 'पेज मजकूर व इमेज CMS',
    cmsTitle: 'वेबसाइट मजकूर व इमेज CMS',
    cmsDesc: 'संपूर्ण वेबसाइटवरील मुख्य शीर्षके, वर्णन, आकडेवारी आणि इमेज लिंक्स संपादित करा.',
    resetDefaults: 'डिफॉल्ट रीसेट करा',
    subTabHero: 'हीरो बॅनर स्लाइडर',
    subTabVision: 'व्हिजन आणि मिशन',
    subTabAbout: 'आमच्याबद्दल विभाग',
    subTabStats: 'महत्त्वाची आकडेवारी',
    subTabGallery: 'मीडिया गॅलरी आयटम्स',
    heroSlidesTitle: 'हीरो बॅनर स्लाइड्स',
    heroSlidesSub: 'मुख्यपृष्ठावरील बॅनर स्लाइड्स जोडा, संपादीत करा किंवा हटवा.',
    addNewSlide: '+ नवीन स्लाइड जोडा',
    saveSlides: 'स्लाइड्स जतन करा',
    imageUrlLabel: 'इमेज URL / फाइल पाथ',
    titlePrefixLabel: 'शीर्षक उपसर्ग (ओळ १)',
    highlightWordLabel: 'हायलाइट शब्द',
    subtitleLabel: 'उपशीर्षक / स्पष्टीकरण',
    vmSectionTitle: 'व्हिजन आणि मिशन विभाग मजकूर',
    vmSectionSub: 'शीर्षके, स्पष्टीकरण आणि मुख्य मुद्दे संपादित करा.',
    saveVm: 'व्हिजन आणि मिशन जतन करा',
    aboutUsCmsTitle: 'आमच्याबद्दल विभाग',
    aboutUsCmsSub: 'मुख्यपृष्ठ "आमच्याबद्दल" विभागाचे शीर्षक आणि वर्णन संपादित करा.',
    saveAboutUs: 'आमच्याबद्दल जतन करा',
    sectionBadgeTag: 'विभाग बॅज टॅग',
    mainTitleLabel: 'मुख्य शीर्षक',
    mainDescLabel: 'मुख्य वर्णन मजकूर',
    keyStatsCmsTitle: 'महत्त्वाची प्रभाव आकडेवारी',
    keyStatsCmsSub: 'रक्तदाते संख्या, दान केलेले युनिट्स, संलग्न रुग्णालये आणि शिबीर संख्या संपादित करा.',
    saveStats: 'आकडेवारी जतन करा',
    labelHappyDonors: 'नोंदणीकृत आनंदी रक्तदाते',
    labelUnitsDonated: 'दान केलेले रक्त युनिट्स',
    labelPartnerHospitals: 'संलग्न रुग्णालये',
    labelCampsCount: 'आयोजित रक्तदान शिबीरे',
    galleryCmsTitle: 'मीडिया गॅलरी आयटम्स',
    galleryCmsSub: 'नवीन बातमी कत्रण जोडा, शीर्षके/मजकूर संपादीत करा किंवा हटवा.',
    addNewNewspaperItem: '+ बातमी कत्रण जोडा',
    saveGalleryItems: 'गॅलरी आयटम्स जतन करा',
    headlineTitleLabel: 'हेडलाइन / शीर्षक',
    subtextSummaryLabel: 'मजकूर / सारांश',
    dateLabel: 'दिनांक',
    locationSourceLabel: 'ठिकाण / स्रोत',
    subTabContact: 'संपर्क माहिती',
    subTabOther: 'पात्रता आणि शिबीर पेज',
    contactCmsTitle: 'संपर्क पान माहिती',
    contactCmsSub: 'आपत्कालीन हेल्पलाइन नंबर, ईमेल, मुख्य कार्यालयाचा पत्ता आणि स्पष्टीकरण संपादित करा.',
    emergencyLineLabel: '२४/७ आपत्कालीन हेल्पलाइन / फोन',
    emailInquiryLabel: 'सामान्य ईमेल चौकशी',
    headquartersLabel: 'मुख्य कार्यालयाचा पत्ता',
    contactDescLabel: 'संपर्क माहिती स्पष्टीकरण',
    otherCmsTitle: 'पात्रता निकष आणि रक्तदान शिबीर CMS',
    otherCmsSub: 'पब्लिक पानांवर प्रदर्शित होणारे स्पष्टीकरण आणि पात्रता नियम संपादित करा.',
    campsSubtitleLabel: 'रक्तदान शिबीर पान स्पष्टीकरण',
    eligSubtitleLabel: 'पात्रता पान स्पष्टीकरण',
    ageDescLabel: 'वयोमर्यादा स्पष्टीकरण',
    weightDescLabel: 'वजन निकष स्पष्टीकरण',
    hemoDescLabel: 'हिमोग्लोबिन पातळी स्पष्टीकरण',
    intervalDescLabel: 'रक्तदाना मधील अंतर स्पष्टीकरण',
    saveContact: 'संपर्क माहिती जतन करा',
    saveOther: 'पान नियम जतन करा',
    subTabAboutPage: 'आमच्याबद्दल पान CMS',
    subTabDonatePage: 'रक्तदान पान CMS',
    subTabGalleryPage: 'मीडिया गॅलरी पान CMS',
    aboutPageCmsTitle: 'आमच्याबद्दल पान मजकूर व आकडेवारी कार्ड्स',
    aboutPageCmsSub: 'शीर्षक, स्पष्टीकरण आणि आकडेवारी कार्ड्स संपादित करा किंवा नवीन जोडा.',
    addNewStatCard: '+ नवीन कार्ड जोडा',
    saveAboutPage: 'आमच्याबद्दल पान जतन करा',
    donateCmsTitle: 'रक्तदान पान हेडर',
    donateCmsSub: 'रक्तदाता नोंदणी पानाचे शीर्षक आणि उपशीर्षक संपादित करा.',
    saveDonate: 'रक्तदान पान जतन करा',
    galleryHeaderCmsTitle: 'गॅलरी पान बॅनर व कत्रणे',
    galleryHeaderCmsSub: 'शीर्षक, उपशीर्षक, टॅग आणि बातम्यांची कत्रणे संपादित करा.',
    badgeLabel: 'बॅज / टॅग लाइन',
    statValueLabel: 'आकडा (उदा. 100%, 200+, Zero)',
    statLabelText: 'कार्ड लेबल मजकूर',
    aboutPageTitle: 'आमच्याबद्दल',
    aboutPageSubtitle: 'ब्लड ट्रस्ट हे स्वयंच्छिक रक्तदात्यांना प्रमाणित रुग्णालयांशी जोडणारे बिनफासटी नेटवर्क आहे.',
    aboutPagePurposeTitle: 'आमचे उद्दिष्ट आणि मुख्य मूल्ये',
    aboutPagePurposeDesc1: 'देशभरात १००% स्वयंच्छिक, डिजिटली कनेक्टेड रक्तदाता नेटवर्क तयार करणे जिथे कोणत्याही आपत्कालीन रुग्णाला सुरक्षित रक्ताच्या अभावामुळे त्रास सहन करावा लागणार नाही.',
    aboutPagePurposeDesc2: 'नागरिकांना सुलभ साधनांद्वारे सक्षम करणे, नियमित रक्तदान शिबिरे आयोजित करणे, तरुणांना शिक्षित करणे आणि गंभीर प्रसंगी इच्छूक दात्यांना रुग्णालयांशी जोडणे.',
    zeroFees: 'शून्य व्यावसायिक शुल्क',
    isoCertified: 'आयएसओ प्रमाणित प्रोटोकॉल',

    // Additional Page & Component UI Translations
    ageLimit: 'वयोमर्यादा',
    ageLimitDesc: '१८ ते ६५ वयोगटातील.',
    minWeight: 'किमान वजन',
    minWeightDesc: 'मानक ४५० मिली रक्तादानासाठी किमान ५० किग्रॅ.',
    hemoglobinLevel: 'हिमोग्लोबिन पातळी',
    hemoglobinLevelDesc: 'रक्तदानापूर्वी चाचणीत किमान १२.५ ग्रॅम/डीएल.',
    donationInterval: 'रक्तदानामधील अंतर',
    donationIntervalDesc: 'पुरुषांसाठी ९० दिवस (३ महिने); महिलांसाठी १२० दिवस (४ महिने).',
    qAge: 'आपले वय १८ ते ६५ दरम्यान आहे का?',
    qWeight: 'आपले वजन किमान ५० किग्रॅ आहे का?',
    qGap: 'आपल्या शेवटच्या रक्तादानाला किमान ३ महिने झाले आहेत का?',
    eligibleSuccessTitle: 'प्राथमिक मूल्यमापन: पात्र',
    eligibleSuccessDesc: 'आपण मूळ आरोग्य निकष पूर्ण करत आहात. जीवन वाचवण्यासाठी नोंदणी करा.',
    ineligibleTitle: 'प्राथमिक मूल्यमापन: अपात्र',
    ineligibleDesc: 'कृपया रक्तदान करण्यापूर्वी वैद्यकीय मार्गदर्शक तत्त्वांचे पुनरावलोकन करा.',
    mediaRecognition: 'प्रसिद्धी व गौरव',
    gallerySubtitle: 'वाचवलेले प्राण, पुन्हा मिळालेली आशा. आमचे वृत्तपत्र कत्रण आणि पुरस्कार पहा.',
    viewFullDetails: 'पूर्ण माहिती पहा',
    details: 'सविस्तर',
    pressClipping: 'वृत्तपत्र बातमी',
    viewAllClippings: 'गॅलरीत सर्व २० बातम्या पहा',
    emergencyLine: '२४/७ आपत्कालीन हेल्पलाइन',
    emailInquiry: 'ईमेल चौकशी',
    headquarters: 'मुख्य कार्यालय',
    yourName: 'आपले नाव',
    yourEmail: 'आपला ईमेल',
    subject: 'विषय',
    message: 'संदेश',
    sendMessage: 'संदेश पाठवा',
    messageSent: 'संदेश यशस्वीरित्या पाठवला!',
    messageSentDesc: 'ब्लड ट्रस्टशी संपर्क साधल्याबद्दल धन्यवाद. आमची टीम २४ तासांच्या आत संपर्क साधेल.',
    sendAnother: 'दुसरा संदेश पाठवा'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('appLanguage') || 'en';
  });

  const setLanguage = (lang) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
